services:
  # API Gateway
  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    environment:
      - ORDER_SERVICE=${ORDER_SERVICE}
      - USER_SERVICE=${USER_SERVICE}
      - PRODUCT_SERVICE=${PRODUCT_SERVICE}
    depends_on:
      - user-service
      - order-service
      - product-service

  # User Service
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGO_URI}/user-service
    depends_on:
      - mongo

  # Order Service
  order-service:
    build:
      context: ./services/order-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=${MONGO_URI}/order-service
      - USER_SERVICE_URL=${USER_SERVICE}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE}
    depends_on:
      - mongo

  # Product Service
  product-service:
    build:
      context: ./services/product-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=${MONGO_URI}/product-service
      - USER_SERVICE_URL=${USER_SERVICE}
      - ORDER_SERVICE_URL=${ORDER_SERVICE}
    depends_on:
      - mongo

  # Payment Service
  payment-service:
    build:
      context: ./services/payment-service
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=${MONGO_URI}/payment-service
      - USER_SERVICE_URL=${USER_SERVICE}
      - ORDER_SERVICE_URL=${ORDER_SERVICE}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE}
    depends_on:
      - mongo
      - user-service
      - order-service
      - product-service
  # MongoDB
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
